// Generated by https://quicktype.io


export class Usuario {
  id:         number;
  email:      string;
  first_name: string;
  last_name:  string;
  avatar: string;
  
  constructor(id: number, email: string, first_name: string,last_name: string, avatar: string){}
}